### ISSUE TITLE
"Maximum call stack size exceeded" error in Chrome-based browsers when starting a map

### ISSUE THREAD

**Issue by mclau152** [Codename-Recon/Gridlock#172]
**Describe the bug**
https://codename-recon.github.io/Gridlock/ loads but you cannot play anything

**To Reproduce**
1. Go to https://codename-recon.github.io/Gridlock/ loads but you cannot play anything
2. Hit play
3. Hit the only option play against AI
4. Pick a map
5. Hit start
6. No response

**Expected behavior**
Game should start after hitting start

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: Edge
 - Game version v0.7.5

**Comment by Dracks** [comment]
Do you have any error in the logs? 

Which version of godot are you using?

**Comment by HunterNN** [comment]
It looks like Chrome-based browsers throw "Maximum call stack size exceeded". I tried it with Edge on Windows and Chromium on Linux:

![Screenshot_20241121_095443](https://github.com/user-attachments/assets/7f123bf9-84bf-4f52-8af8-ab04da9e7de4)
