### ISSUE TITLE
Implement CSV-based credit generation system

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Gridlock#21]
In order to streamline the credit generation process for the game, we need to implement a new system that utilizes a .cvs (Comma Separated Values) file. This will allow us to easily update and manage the credits within the game.

The system should be able to read the .cvs file, parse the data, and use it to generate the appropriate credits for the game. It is important that this system is flexible and easy to maintain, as we may need to make updates to the credit values in the future.

The .cvs file containing the credit data should be placed in the following directory: `res://doc/credits.cvs`

Once the credits have been generated from the .csv file, they can be stored as a text asset under the level named *menu* in the following path *Menu -> Credits -> Panel ScrollContainer -> RichTextLabel*

The credit values should be generated as soon as the editor is launched: https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html

The structure of the credit.csv file should be such that each row represents an entry, and the following columns should be provided:

- **Name / Author** *String*: The name of the author or creator of the entry or provided assets.
- **Title / Provided Assets** *String*
- **External** *Flag*
- **URL to a landing page / Source URL** *String*: The original source of the provided assets, if they were created external.
- **Description** *String*: A brief description of the entry or provided assets. (external)
- **Date Added** *Date/Datetime*: The date on which the entry was added to the file.
- **Last Updated** *Date/Datetime*: The date on which the entry was last updated in the file.
- **License** *String*: Information about the license under which the provided assets are made available, if applicable. (external)

Which information should also be generated for in-game view needs to be discussed with the UI team.

**Comment by Dracks** [comment]
what is your idea for the csv? having a column/row per context? like a column for programmers, another one for dessigners, etc? 

Isn't there any better format for that? or your idea is that mangs can modify it?

**Comment by HunterNN** [comment]
In larger projects, it is common to use a CSV or Excel file to compile credits, as this allows for easy handling by multiple team members. However, if there exists an in-engine solution that can represent a spreadsheet, we could consider using this instead of the CSV file.

I've added the spreadsheet structure to the opening post of the issue

**Comment by Dracks** [comment]
With the problems we have with the initial import and the CSV translations, I think the CSV will make reapear the problem. 

Maybe one solution will be to save the file with another extension? (we should check it)

**Comment by HunterNN** [comment]
We could also consider using a different file format, but I'm not sure which one would be most suitable. Ultimately, it should be easy for non-technical users to edit.

**Comment by Dracks** [comment]
I just check, if we add a credits.csv that is not a translation, the #85 reapears!

I'm thinking, that maybe will be nice to add some logic/way in the pipeline to validate that's not there. 

My proposal will be to add some file credits without .csv and this stuff, since with that we should be able to load it from code

**Comment by HunterNN** [comment]
What about creating a Godot plugin to manage credits within the editor and save them as a resource?

**Comment by Dracks** [comment]
that's what I've got in mind, more or less, maybe there is some asset already?

**Comment by HunterNN** [comment]
Closing this issue since credit management is now handled through the markdown file.
